title: "曾大猫的sketchup笔记"
author: "Zdamao"
description: "Sketchup的使用、插件和插件开发"
more: "read more »"
url: "https://cgclip.com"
baseurl: "/contrast"
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - about.md

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - twitter: "https://twitter.com/twitter/"
  - github: "https://github.com/niklasbuschmann/contrast"
  - envelope: "mailto:niklas.buschmann@posteo.de"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]

theme: jekyll-theme-architect